# Generated by Django 6.0.3 on 2026-04-13 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locais')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.responsaveis')),
            ],
        ),
        migrations.CreateModel(
            name='Microcontroladores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.BooleanField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambientes')),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sensor', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('UMIDADE', 'Umidade'), ('LUMINOSIDADE', 'Luminosidade'), ('PRESENCA', 'Presença')], max_length=100)),
                ('unidade_medida', models.CharField(choices=[('C', 'Celsius'), ('%', 'Porcentagem'), ('LUX', 'Lux'), ('UNI', 'Uni')], max_length=100)),
                ('status', models.BooleanField()),
                ('mic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.microcontroladores')),
            ],
        ),
        migrations.CreateModel(
            name='Historicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensores')),
            ],
        ),
    ]
